//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JupiterEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartProds = new HashSet<CartProd>();
            this.ProductMedias = new HashSet<ProductMedia>();
        }
    
        public int ProdId { get; set; }
        public Nullable<int> ProdTypeId { get; set; }
        public Nullable<int> CategroyId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> TotalStock { get; set; }
        public Nullable<int> AvailableStock { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> SpcOrDisct { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SpecialPrice { get; set; }
        public Nullable<byte> IsActivate { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartProd> CartProds { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMedia> ProductMedias { get; set; }
    }
}
